[QEMU]
TITLE					= "Ubuntu 24.04"
ACCELERATION			= whpx
SMP_SIZE				= 2
MEMORY_SIZE				= 4096
FULL_SCREEN				= false
VGA						= virtio
DISPLAY					= sdl,gl=on
HARD_DISK_IMAGE			= qemu_testdrive.qcow2
HARD_DISK_SIZE			= 20G
BOOT_FROM_CDROM			=false
CDROM_IMAGE				= ubuntu-24.04.4-desktop-amd64.iso
KERNEL_IMAGE			=
RAM_DISK_IMAGE			=
BOOT_COMMAND			=
EXTRA_OPTIONS			= -netdev user,id=net0,smb=D:/Download -device virtio-net-pci,netdev=net0
;EXTRA_OPTIONS			= -net nic,model=virtio-net-pci -net user
;EXTRA_OPTIONS			= -net user,smb=D:/Download -net nic,model=virtio
;refresh will be occur every 100 days
;AUTO_REFRESH_DAYS		= 100

[TESTDRIVE_DEVICE]
MAIN_VENDOR_ID			= 0x1234
MAIN_DEVICE_ID			= 0x0000
SUB_VENDOR_ID			= 0x0000
SUB_DEVICE_ID			= 0x0000
CLASS_ID				= 0x0780
REVISION				= 0x00
;ROM_FILE				= testdrive_device.rom
SETUP_SCRIPT			= ../testdrive_device_setup.lua
