[QEMU]
TITLE					= "BusyBox"
ACCELERATION			= whpx
SMP_SIZE				= 2
MEMORY_SIZE				= 1024
FULL_SCREEN				= false
VGA						=
DISPLAY					= sdl
HARD_DISK_IMAGE			=
HARD_DISK_SIZE			=
BOOT_FROM_CDROM			=false
CDROM_IMAGE				= 
KERNEL_IMAGE			= vmlinuz
RAM_DISK_IMAGE			= initramfs.gz
BOOT_COMMAND			= "console=ttyS0 rdinit=/etc/init panic=-1"
EXTRA_OPTIONS			= -nodefaults -serial stdio -net nic,model=virtio -net user

[TESTDRIVE_DEVICE]
MAIN_VENDOR_ID			= 0x1234
MAIN_DEVICE_ID			= 0x0000
SUB_VENDOR_ID			= 0x0000
SUB_DEVICE_ID			= 0x0000
CLASS_ID				= 0x0780
REVISION				= 0x00
;ROM_FILE				= testdrive_device.rom
SETUP_SCRIPT			= ../testdrive_device_setup.lua
