#-------------------------------------------------
# Project
#-------------------------------------------------
SRC_PATH		:= .
TARGETPATH		:= ..
TARGETNAME		:= DesignMap

SRCS			:= \
	$(SRC_PATH)/DesignMap.cpp

INC				:=

#-------------------------------------------------
# common document config
#-------------------------------------------------
include $(TESTDRIVE_PROFILE)/common/include/config_document.mk
