LOGI("LOGI test.")
LOGW("LOGW test.")
LOGE("LOGE test.")
print("exec('pwd') : " .. exec("pwd"))
print("run('pwd') : " .. run("pwd"))
-- Sleep(1000)
-- Pause()
print("IsWindows() : " .. tostring(IsWindows()))
print("GetCommonToolPath() : " .. GetCommonToolPath())
print("log.error_count : " .. log.error_count)
print("log.warning_count : " .. log.error_count)
print("codegen.ArgumentSize() : " .. codegen.ArgumentSize())
print("codegen.current_file : " .. codegen.current_file)
print("codegen.work_path : " .. codegen.work_path)
print("codegen.env_path : " .. codegen.env_path)
