#-------------------------------------------------
# Project
#-------------------------------------------------
SRC_PATH		:= .
TARGETNAME		:= make_testbench

SRCS			:= \
	$(wildcard $(SRC_PATH)/*.cpp)
	
INC				:= 
CDEFS			:= -DUSE_TESTDRIVE

#-------------------------------------------------
# common document config
#-------------------------------------------------
include $(TESTDRIVE_PROFILE)Common/utils/include/util.mk
