#-------------------------------------------------
# Project
#-------------------------------------------------
SRC_PATH		:= .
TARGETNAME		:= tlink

SRCS			:= \
	$(wildcard $(SRC_PATH)/*.cpp)
	
INC				:= -I../include
CDEFS			:=

#-------------------------------------------------
# common document config
#-------------------------------------------------
include ../include/util.mk

