#-------------------------------------------------
# Project
#-------------------------------------------------
SRC_PATH		:= .
TARGETPATH		:= ..
TARGETNAME		:= StarterKit

SRCS			:= \
	$(wildcard $(SRC_PATH)/*.cpp)

INC				:=
LIBDIR			:= -lwinmm
#-------------------------------------------------
# common document config
#-------------------------------------------------
include $(TESTDRIVE_PROFILE)/common/include/config_document.mk
