#-------------------------------------------------
# Project
#-------------------------------------------------
SRC_PATH		:= .
TARGETNAME		:= DependencyPrepare
INSTALL_PATH	:= $(TESTDRIVE_PROFILE)Common/bin
SRCS			:= \
	$(wildcard $(SRC_PATH)/*.cpp)
	
INC				:= -I../include
CDEFS			:=

#-------------------------------------------------
# common document config
#-------------------------------------------------
include ../include/util.mk

