#-------------------------------------------------
# Project
#-------------------------------------------------
SRC_PATH		:= .
TARGETPATH		:= .
TARGETNAME		:= iStyle
INSTALL_PATH	:= $(TESTDRIVE_PROFILE)Common/bin
#USE_DEBUG		:= 1			# comment out if you not need a debug mode
CPP_STANDARD	:= c++14		# C++ standard
#MAIN_COMPILER	:= clang		# uncomment this to use clang compiler (default : gcc)

SRCS			:= \
	$(wildcard $(SRC_PATH)/*.cpp)
	
INC				:=

CDEFS			:= -s
CFLAGS			:=

#-------------------------------------------------
# common document config
#-------------------------------------------------

BUILD_TARGET	= $(TARGET_EXE)

include $(TESTDRIVE_PROFILE)/common/include/config.mk
