#-------------------------------------------------
# Project
#-------------------------------------------------
SRC_PATH		:= .
TARGETPATH		:= .
TARGETNAME		:= iStyle
INSTALL_PATH	:= $(TESTDRIVE_PROFILE)Common/bin
SRCS			:= \
	$(wildcard $(SRC_PATH)/*.cpp)
	
INC				:=

CDEFS			:= -s
CFLAGS			:=
EXTRA_CFLAGS	:= -O3 -std=c++14 -DNDEBUG

#-------------------------------------------------
# common document config
#-------------------------------------------------

BUILD_TARGET	= $(TARGET_EXE)

include $(TESTDRIVE_PROFILE)/common/include/config.mk
