#-------------------------------------------------
# Project
#-------------------------------------------------
SRC_PATH		:= .
TARGETPATH		:= ..
TARGETNAME		:= ScenarioTest

SRCS			:= \
	$(SRC_PATH)/HtmlTable.cpp \
	$(SRC_PATH)/TestVector.cpp \
	$(SRC_PATH)/TestGroup.cpp \
	$(SRC_PATH)/TestList.cpp \
	$(SRC_PATH)/ScenarioTest.cpp \
	$(SRC_PATH)/common.cpp

INC				:=

#-------------------------------------------------
# common document config
#-------------------------------------------------
include $(TESTDRIVE_PROFILE)/common/include/config_document.mk
