#-------------------------------------------------
# common document config
#-------------------------------------------------
MAKEFLAGS	+= --silent
include $(TESTDRIVE_PROFILE)Common/System/SystemSim/SimHDL/SimHDL.mk