#-------------------------------------------------
# Project
#-------------------------------------------------
SRC_PATH		:= .
TARGETNAME		:= code_highlighter

SRCS			:= \
	$(wildcard $(SRC_PATH)/*.cpp)
	
INC				:= -I../include
LIBDIR			:= -lsource-highlight
CDEFS			:=

#-------------------------------------------------
# common document config
#-------------------------------------------------
include ../include/util.mk

