#-------------------------------------------------
# Project
#-------------------------------------------------
SRC_PATH		:= .
TARGETPATH		:= ..
TARGETNAME		:= ALUTest

SRCS			:= \
	$(SRC_PATH)/ALUTest.cpp \
	$(SRC_PATH)/SimALU.cpp

INC				:=

#-------------------------------------------------
# common document config
#-------------------------------------------------
include $(TESTDRIVE_PROFILE)/common/include/config_document.mk
