[QEMU]
TITLE					= "TestDrive"
;x86_64(default), aarch64, riscv64, ppc64
SYSTEM					= x86_64
HYPERVISOR_ACCEL		= true
SMP_SIZE				= 2
MEMORY_SIZE				= 4096
FULL_SCREEN				= false
VGA						= virtio
DISPLAY					= sdl,gl=on
HARD_DISK_IMAGE			= qemu_testdrive.qcow2
HARD_DISK_SIZE			= 20G
BOOT_FROM_CDROM			= true
CDROM_IMAGE				= 
TESTDRIVE_DEVICE		= true
KERNEL_IMAGE			=
RAM_DISK_IMAGE			=
BOOT_COMMAND			=
EXTRA_OPTIONS			=

[PCI]
; INTERFACE : conventional-pci-device, pci-express-device(default), cxl-device
INTERFACE				= pci-express-device
MAIN_VENDOR_ID			= 0x3323
MAIN_DEVICE_ID			= 0x3000
SUB_VENDOR_ID			= 0
SUB_DEVICE_ID			= 0
CLASS_ID				= 0xff
REVISION				= 0
;ROM_FILE				= "testdrive_device.rom"
MSI_VECTOR_COUNT		= 1
MSI_PER_VECTOR_MASK		= false
