#-------------------------------------------------
# Project
#-------------------------------------------------
SRC_PATH		:= ./
LIBPATH			:= ../../lib
TARGETPATH		:= ../../../../Program
TARGETNAME		:= lua
PRESERVE_RESULT	:= 1

SRCS			:= \
	$(wildcard $(SRC_PATH)/*.cpp)

LIBDIR			:= 
INC				:= -I$(SRC_PATH) -I.

CDEFS			:= 
CFLAGS			:= -O3

BUILD_TARGET	= $(TARGET_A)

#-------------------------------------------------
# common document config
#-------------------------------------------------
include $(TESTDRIVE_PROFILE)common/include/config.mk
