#-------------------------------------------------
# Project
#-------------------------------------------------
SRC_PATH		:= .
TARGETPATH		:= .
INSTALL_PATH	:= ..
TARGETNAME		:= meitner_slave

SRCS			:= \
	$(wildcard $(SRC_PATH)/*.cpp)

INC				:= -I../../../Application/include -I$(TESTDRIVE_PROFILE)Common/include

CDEFS			:= 
CFLAGS			:= -O3

#-------------------------------------------------
# common document config
#-------------------------------------------------
BUILD_TARGET	= $(TARGET_EXE)
include $(TESTDRIVE_PROFILE)common/include/config.mk
