#-------------------------------------------------
# Project
#-------------------------------------------------
SRC_PATH		:= .
LIBPATH			:= ../../../Application/lib
TARGETPATH		:= ..
TARGETNAME		:= mtsp_cmd_process

SRCS			:= \
	$(SRC_PATH)/main.cpp

LIBDIR			:=
INC				:= -I../../../Application/include

CDEFS			:= 
LDFLAGS			:= -mwindows

BUILD_TARGET	= $(TARGET_EXE)

#-------------------------------------------------
# common document config
#-------------------------------------------------
include $(TESTDRIVE_PROFILE)common/include/config.mk
