#-------------------------------------------------
# Project
#-------------------------------------------------
TARGETNAME		:= testdrive_pcie

INC				:= -I../../../Driver/windows/inc -I../../../Application/include

#-------------------------------------------------
# common document config
#-------------------------------------------------
include $(TESTDRIVE_PROFILE)common/System/SystemDriver/config.mk
