#-------------------------------------------------
# Project
#-------------------------------------------------
TARGETNAME		:= PCIeDriverSystem

INC				:= -I../../../Driver/windows/inc

#-------------------------------------------------
# common document config
#-------------------------------------------------
include $(TESTDRIVE_PROFILE)common/System/SystemDriver/config.mk
