#-------------------------------------------------
# Project
#-------------------------------------------------
SRC_PATH		:= .
TARGETPATH		:= ..
TARGETNAME		:= SystemRemote

SRCS			:= \
	$(wildcard $(SRC_PATH)/*.cpp)

INC				:=
LIBDIR			:= -lwsock32 -lws2_32

#-------------------------------------------------
# common document config
#-------------------------------------------------
include $(TESTDRIVE_PROFILE)/common/include/config_document.mk
