[QEMU]
TITLE					= "Windows 11 IoT"
;x86_64(default), aarch64, riscv64, ppc64
SYSTEM					= x86_64
ACCELERATION			= whpx
SMP_SIZE				= 2
MEMORY_SIZE				= 6G
FULL_SCREEN				= false
VGA						= virtio
DISPLAY					= sdl,gl=on
HARD_DISK_IMAGE			= qemu_testdrive.qcow2
HARD_DISK_SIZE			= 50G
BOOT_FROM_CDROM			=false
CDROM_IMAGE				= en-us_windows_11_iot_enterprise_ltsc_2024_x64_dvd_f6b14814.iso
KERNEL_IMAGE			=
RAM_DISK_IMAGE			=
BOOT_COMMAND			=
EXTRA_OPTIONS			= -M q35,usb=on,acpi=on,hpet=off
; Attempts a forced refresh every 100 days. 
;AUTO_REFRESH_DAYS		= 100

[TESTDRIVE_DEVICE]
MAIN_VENDOR_ID			= 0x1234
MAIN_DEVICE_ID			= 0x0000
SUB_VENDOR_ID			= 0x0000
SUB_DEVICE_ID			= 0x0000
CLASS_ID				= 0x0780
REVISION				= 0x00
;ROM_FILE				= testdrive_device.rom
SETUP_SCRIPT			= ../testdrive_device_setup.lua