#-------------------------------------------------
# Project
#-------------------------------------------------
SRC_PATH		:= .
TARGETPATH		:= .
TARGETNAME		:= MakeRelease

SRCS			:= \
	$(wildcard $(SRC_PATH)/*.cpp)
	
INC				:= -I../../framework
LIBDIR			:= -L../../lib
CDEFS			:=

#-------------------------------------------------
# common document config
#-------------------------------------------------
include ../../include/util.mk

