#-------------------------------------------------
# Project
#-------------------------------------------------
SRC_PATH		:= .
TARGETPATH		:= .
TARGETNAME		:= MakeRelease
INSTALL_PATH	:= $(TARGETPATH)

SRCS			:= \
	$(wildcard $(SRC_PATH)/*.cpp)
	
INC				:=
LIBDIR			:=
CDEFS			:=

#-------------------------------------------------
# common document config
#-------------------------------------------------
include ../../include/util.mk

