#-------------------------------------------------
# Project
#-------------------------------------------------
SRC_PATH		:= .
TARGETPATH		:= ../../../../Program
TARGETNAME		:= Testbench_ScenarioVector

SRCS			:= \
	$(wildcard $(SRC_PATH)/*.cpp)
	
INC				:= -I../framework

CDEFS			:= -DUSE_TESTDRIVE

#-------------------------------------------------
# common document config
#-------------------------------------------------
include ../../../include/common.mk
