#-------------------------------------------------
# HDL build Project
#-------------------------------------------------
SRCS			:= $(wildcard ./HDL/*)

all: .verilated_src/SimTop.cpp

clean:
	@rm -f .verilated_src/SimTop*

.verilated_src/SimTop.cpp:$(SRCS)
	@rm -f .verilated_src/SimTop*
	@verilator ./HDL/top.v -IHDL -sv -cc --autoflush --compiler gcc -Mdir ./.verilated_src -prefix SimTop --top-module top
	@echo HDL build is done!
