#-------------------------------------------------
# Project
#-------------------------------------------------
SRC_PATH		:= .
TARGETPATH		:= ..
TARGETNAME		:= XilinxSynthesis

SRCS			:= \
	$(SRC_PATH)/XilinxSynthesis.cpp \
	$(SRC_PATH)/XilinxToolCheck.cpp \
	$(SRC_PATH)/XilinxDevices.cpp \
	$(SRC_PATH)/ProjectTable.cpp \
	$(SRC_PATH)/ProjectConfig.cpp \
	$(SRC_PATH)/SourceList.cpp \
	$(SRC_PATH)/HtmlTable.cpp

INC				:=

#-------------------------------------------------
# common document config
#-------------------------------------------------
include $(TESTDRIVE_PROFILE)/common/include/config_document.mk
