#-------------------------------------------------
# Project
#-------------------------------------------------
SRC_PATH		:= .
TARGETPATH		:= $(TESTDRIVE_DIR)/bin/
TARGETNAME		:= install_notepad_plugin
PRESERVE_RESULT	:= 1

SRCS			:= \
	$(wildcard $(SRC_PATH)/*.cpp) \
	$(wildcard $(SRC_PATH)/*.c)
	
INC				:= -I../common -I.
LIBDIR			:=
CDEFS			:=
#MAIN_COMPILER	:= clang		# uncomment this code to using clang compiler

#-------------------------------------------------
# common util config
#-------------------------------------------------
include ../include/util.mk