#-------------------------------------------------
# SimSystem makefile
#-------------------------------------------------
MAKEFLAGS	+= --silent
include $(TESTDRIVE_PROFILE)common/System/SystemSim/SimSystem/Makefile
